version: '3.3'
services:
    node-exporter:
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
        image: 'quay.io/prometheus/node-exporter:latest'

    prometheus:
        container_name: prometheus
        #uncomment next 2 lines for multinode cluster use
        #ports:
        #    - '9091:9090'
        volumes:
            - './prometheus.yml:/etc/prometheus/prometheus.yml'
        image: prom/prometheus
        restart: unless-stopped

    grafana:
        container_name: grafana
        ports:
            - '3000:3000'
        image: grafana/grafana
        restart: unless-stopped
        #Explicitly define the persistent volume for your data storage
        volumes:
            - grafana-data:/var/lib/grafana
        #Optional environmental settings for access by subpath
        environment:
            GF_SERVER_ROOT_URL: "/monitoring"
            GF_SERVER_SERVE_FROM_SUB_PATH: "true"
volumes:
  grafana-data:
